### ISSUE TITLE
Custom Map

### ISSUE THREAD

**Issue by brunocarneiro** [wouterbulten/slacjs#14]
Hi Wouter,

I took a look at your code and I really appreciate the overall quality.
However I have one question about SLAC. Is it possible to use custom map. E.g.: Use an existent mall map.

If so, how can I tell SLAC what is the sampling starting point (on the custom map).

By the way, I tried to find your personal email in your website or here but I couldn't. That's why I opened an issue. I would appreciate if we could discuss some technical stuff about SLAC and IPS through email. You can reach me by bjcarneiro@gmail.com
Thank you

**Comment by wouterbulten** [comment]
Yes and no. There is no direct support for custom maps. Though, the map representation uses a normal canvas element which you could extend and add an image to. Another approach would be to make the canvas transparent and add your map as a background image.

The starting point would be a bit more difficult. The rendered scales up when you walk out of the frame of the map so you would have to update that functionality or remove it. Take a look at https://github.com/wouterbulten/slacjs/blob/master/src/app/view/particle-renderer.js which is the default renderer for the mobile app.

**Comment by brunocarneiro** [comment]
Thank you for your answer Wouter.
I'll take a look and try an approach!

**Comment by wouterbulten** [comment]
Good luck! Would be very interested in your approach.

(Will close the issue for now)
